#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: '20181050250'
      #password 密码
      password: 'fzhAzsl1314'
      #address 地址，定位信息
      address: 中国山东省德州市德城区长河街道
      #email 接受通知消息的邮箱
      email: 2648182958@qq.com
      #school 学校全称
      school: 山东华宇工学院
      #lon 经度
      lon: '116.366657'
      #lat 纬度
      lat: '37.469523'
      #abnormalReason 反馈信息
      abnormalReason:
    
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:
  defaults:
  #附加信息组默认选项配置，没有可留空
  - default:
      title: 昨晚体温度数
      value: 36.5
- default:
      title: 今天上午体温度数
      value: 36.5

- default:
      title: 今天下午体温度数
      value: 36.5
